### 1. Object x <-1:15
Construct a 5x3 matrix for the value of x. 

In [178]:
x <- 1:15 
matrix(x, nrow=5, ncol=3)

[,1] [,2] [,3]
[1,] 1     6   11  
[2,] 2     7   12  
[3,] 3     8   13  
[4,] 4     9   14  
[5,] 5    10   15

### 2. Write a program to generate the following 4x4 matrix 
0 0 0 0 

0 0 0 0 

0 0 0 0 

0 0 0 0 

In [179]:
matrix(0,nrow=4, ncol=4)

[,1] [,2] [,3] [,4]
[1,] 0    0    0    0   
[2,] 0    0    0    0   
[3,] 0    0    0    0   
[4,] 0    0    0    0

### 3. The object x<-1:8 
Write a program to generate the following 3x8 matrix using "cbind(),rbind(),rev(),rep()" 

1 2 3 4 5 6 7 8 

8 7 6 5 4 3 2 1 

3 3 3 3 3 3 3 3 

In [180]:
x <- 1:8
rbind(unname(x),rev(x),rep(3,8))


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    2    3    4    5    6    7    8   
[2,] 8    7    6    5    4    3    2    1   
[3,] 3    3    3    3    3    3    3    3

### 4. Chose two different(x,y) 4x4 matrix to perform the following arithmetic operations 

(a). x + y 

(b). x - y 

(c). x*y 

(d). x%*%y 

(e). Difference between (c) &(d) 

(f). Inverse of y 

(g). z<-x/y 

(h). Transpose of z 

(i). Diagonal of transpose matrix 

In [181]:
x <- matrix(1:16, nrow=4)
y <- matrix(2:17, nrow=4)

### (a). x + y 
x+y

[,1] [,2] [,3] [,4]
[1,] 3    11   19   27  
[2,] 5    13   21   29  
[3,] 7    15   23   31  
[4,] 9    17   25   33

In [182]:
### (b). x - y 
x-y

[,1] [,2] [,3] [,4]
[1,] -1   -1   -1   -1  
[2,] -1   -1   -1   -1  
[3,] -1   -1   -1   -1  
[4,] -1   -1   -1   -1

In [183]:
### (c). x * y 
x*y

[,1] [,2] [,3] [,4]
[1,]  2   30    90  182 
[2,]  6   42   110  210 
[3,] 12   56   132  240 
[4,] 20   72   156  272

In [184]:
### (d). x%*%y 
x%*%y 

[,1] [,2] [,3] [,4]
[1,] 118  230  342  454 
[2,] 132  260  388  516 
[3,] 146  290  434  578 
[4,] 160  320  480  640

#### (e). Difference between (c) & (d) 
1. (c) is Element Multiplication : each element of x multiple to each element of y

2. (d) is Matrix Product: **Martrix(y)** product to **Matrix(y)**


In [185]:
### (f). Inverse of y 
library(MASS)
ginv(y)

[,1]    [,2]   [,3]    [,4] 
[1,] -0.3075 -0.115  0.0775  0.27
[2,] -0.1525 -0.055  0.0425  0.14
[3,]  0.0025  0.005  0.0075  0.01
[4,]  0.1575  0.065 -0.0275 -0.12

In [186]:
### (g). z<-x/y
z <- x/y
z

[,1]      [,2]      [,3]      [,4]     
[1,] 0.5000000 0.8333333 0.9000000 0.9285714
[2,] 0.6666667 0.8571429 0.9090909 0.9333333
[3,] 0.7500000 0.8750000 0.9166667 0.9375000
[4,] 0.8000000 0.8888889 0.9230769 0.9411765

In [187]:
### (h). Transpose of z 
transpose <- t(z)
transpose

[,1]      [,2]      [,3]      [,4]     
[1,] 0.5000000 0.6666667 0.7500000 0.8000000
[2,] 0.8333333 0.8571429 0.8750000 0.8888889
[3,] 0.9000000 0.9090909 0.9166667 0.9230769
[4,] 0.9285714 0.9333333 0.9375000 0.9411765

In [188]:
### (i). Diagonal of transpose matrix 
diag(diag(transpose))

[,1] [,2]      [,3]      [,4]     
[1,] 0.5  0.0000000 0.0000000 0.0000000
[2,] 0.0  0.8571429 0.0000000 0.0000000
[3,] 0.0  0.0000000 0.9166667 0.0000000
[4,] 0.0  0.0000000 0.0000000 0.9411765

### 5. Difference between (i) & (ii) 

(i). x<-matrix(x<-1:9,3,3,byrow = TRUE) 

(ii). x<-matrix(x<-1:9,3,3) 

### The Difference between (i) & (ii) is:
1. (i) the matrix is created by filling the value from Vector by row fist
2. (ii) the matrix is created by filling the value from vector by col fist (the defualt filling in matrix)

### 6. Which function can we use for inner product and outer product in matrix calculation?
* Function for inner product is %*%
* Function for outer product is %o%


### 7. Explain the use of all.equal() function in Matrix with a sample program. 

all.equal() function in Matrix is used to compare the 2 matrix to check that 2 matrix is nearly equal or exactly equal or not and return mean of the different.

In [189]:
# Program to compare x with y that x is the target.
all.equal(x,y)

[1] "Mean relative difference: 0.1176471"

### 8. Explain the use of dim() function with a sample program. 
dim() function is used to get the dimensions of matrix. It return 2 integer number that the fist one indicate number of row and second number indicate number of column.

In [190]:
# get dimension of matrix(x) (4x4 matrix).
dim(x)

[1] 4 4

### 9. Use of $ operator, and square brackets [] in List with example program.

* $ operator in List is used for access the Element in the list by name.
* [] square brackets operator in List is used for access the element in the List by index.

In [196]:
#Example
l <- list(name = "kimteng", weight = 70, height = 172, student = TRUE)

"access with $ operator"
l$name
l$weight

"access with [] operator"
l[1]
l[1:3]


[1] "access with $ operator"

[1] "kimteng"

[1] 70

[1] "access with [] operator"

$name
[1] "kimteng"

$name
[1] "kimteng"

$weight
[1] 70

$height
[1] 172

### 10. Explain ifelse() with example. 
ifelse() function is used for convert one variable to other variables base on logical expression or conditions. It requires 3 paramater is:
1. the logical expression or condiction
2. the return value if the condiction is true
3. the return value if the condiction is false

In [192]:
# check element of matrix(x) is odd or even
ifelse(x %% 2 == 0,"even","odd")

[,1] [,2] [,3] [,4]
[1,] odd  odd  odd  odd 
[2,] even even even even
[3,] odd  odd  odd  odd 
[4,] even even even even

### 11. Write a program to get the weight and height from the user to calculate the following cases 

a. If your BMI is less than 18.5, it falls within the underweight range. 

b. If your BMI is 18.5 to <25, it falls within the normal.

c. If your BMI is 25.0 to <30, it falls within the overweight range. 

d. If your BMI is 30.0 or higher, it falls within the obese range. 

In [193]:
w <- as.numeric(readline(prompt="Enter weight(kg): "))
h <- as.numeric(readline(prompt="Enter height(m): "))
bmi <- w/h^2
if(bmi<18.5){
    "underweight range"
}else if (bmi<25) {
    "normal range"
}else if (bmi<30) {
    "overweight range"
}else{
    "obese range"
}

Enter weight(kg): 70
Enter height(m): 1.72


[1] "normal range"

### 12. Difference between List and Data frame with an example program. 
* List is the array of element of same or different type that store in sequence.
* Data Frame is the matrix of the same or different type that store in the form of row and column.

In [194]:
# List
list(4, TRUE , "John", 7, FALSE, "Mary")

# Data Frame
weight <- c( 150, 170, 160, 190)
height <- c( 67, 70, 65, 68)
data.frame(Weight = weight, Height = height)

[[1]]
[1] 4

[[2]]
[1] TRUE

[[3]]
[1] "John"

[[4]]
[1] 7

[[5]]
[1] FALSE

[[6]]
[1] "Mary"

Weight Height
1 150    67    
2 170    70    
3 160    65    
4 190    68

### 13. Difference between repeat and while loop with example program. 
* Repeat is the loop that requires you to explicitly break the loop on your own and can be at any point in the body of the loop.
* While is the loop that tests a condition to determine when to finish looping.

In [195]:
"Repeat loop"
i <- 1
repeat {if (i==5) break;print(i);i<-i+1}

"While Loop"
i <- 1
while (i!=5) {print(i);i<-i+1}

[1] "Repeat loop"

[1] 1
[1] 2
[1] 3
[1] 4


[1] "While Loop"

[1] 1
[1] 2
[1] 3
[1] 4
